"""rules embeddings

Revision ID: 4ca8e5d33f3c
Revises: c1ee0c7d10ed
Create Date: 2026-09-24 13:16:22.409425

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4ca8e5d33f3c'
down_revision: str | Sequence[str] | None = 'c1ee0c7d10ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.add_column('rules', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'embedding')
    # ### end Alembic commands ###
