"""rules full-text search

Revision ID: c1ee0c7d10ed
Revises: c90667a0fb69
Create Date: 2026-09-24 12:34:17.253502

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1ee0c7d10ed'
down_revision: str | Sequence[str] | None = 'c90667a0fb69'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', text)", persisted=True), nullable=False))
    op.create_index('ix_rules_tsv', 'rules', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rules_tsv', table_name='rules', postgresql_using='gin')
    op.drop_column('rules', 'tsv')
    # ### end Alembic commands ###
