"""rules: chapters and notes

Revision ID: c90667a0fb69
Revises: 27274a52b341
Create Date: 2026-09-23 16:23:50.229110

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c90667a0fb69'
down_revision: str | Sequence[str] | None = '27274a52b341'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('chapter_number', sa.Integer(), nullable=False))
    op.add_column('rules', sa.Column('chapter_title', sa.String(), nullable=False))
    op.add_column('rules', sa.Column('note', sa.String(), nullable=False))
    op.drop_column('rules', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('rules', 'note')
    op.drop_column('rules', 'chapter_title')
    op.drop_column('rules', 'chapter_number')
    # ### end Alembic commands ###
